---
sudo: required

language: c

services:
  - docker

before_install:
  - docker build -t atgreen/labdroid-minio .

script:
  - ls -l  

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push atgreen/labdroid-minio;
    fi

